CREATE TABLE "Pairs" (
	"id"	INTEGER NOT NULL UNIQUE,
	"phrase"	TEXT NOT NULL,
	"region"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)

CREATE TABLE "TimeStamps" (
	"id"	INTEGER NOT NULL UNIQUE,
	"counter"	TEXT NOT NULL,
	"pair_id"	INTEGER NOT NULL,
	"timestamp"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)

CREATE TABLE "TopPosts" (
	"id"	INTEGER NOT NULL UNIQUE,
	"pair_id"	INTEGER NOT NULL UNIQUE,
	"links"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)

